name: Build and test
on: push

env:
    # we use these in .ci.maven.settings.xml, which is needed to authenticate for core (!) GitHub packages
    MAVEN_SETTINGS_USERNAME_FOR_GITHUB: ${{ secrets.MAVEN_SETTINGS_USERNAME_FOR_GITHUB }}
    MAVEN_SETTINGS_PASSWORD_FOR_GITHUB: ${{ secrets.MAVEN_SETTINGS_PASSWORD_FOR_GITHUB }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    server-id: github
            -   name: Build with Maven
                run: mvn --batch-mode --update-snapshots verify
            -   name: Set jsprit version (tagged only)
                run: mvn versions:set -DnewVersion=${{  github.ref_name }} -DgenerateBackupPoms=false --no-transfer-progress
                if: startsWith(github.ref, 'refs/tags/')
            -   name: Publish to GitHub Packages
                if: startsWith(github.ref, 'refs/tags/')
                run: mvn --batch-mode deploy -B --no-transfer-progress -DskipTests -P release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

