name: GitHub CI

on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Build with Maven
                run: mvn --batch-mode --update-snapshots verify
            -   name: Publish to GitHub Packages
                if: startsWith(github.ref, 'refs/tags/')
                run: mvn --batch-mode deploy
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

